Create arrays with all the data types available in numpy.

In [ ]:
import numpy as np

In [13]:
#boolean
x = np.array([False, True, False, True], dtype = 'bool_')
print(x)
print(x.dtype)

[False  True False  True]
bool


In [14]:
#integer
x = np.array([3, 9, 6], dtype = 'int_')
print(x)
print(x.dtype)

[3 9 6]
int32


In [15]:
#Float
x = np.array([2.3, 5.2, 2.09, 4.01, 2.46], dtype = 'float_')
print(x)
print(x.dtype)

[2.3  5.2  2.09 4.01 2.46]
float64


In [18]:
#string
x = np.array(['a', 'r', 'm'], dtype = 'S')
print(x)
print(x.dtype)

[b'a' b'r' b'm']
|S1


In [9]:
#complex
x = np.array([3+1j, 1-2j, 2+2.2j], dtype = 'complex_')
print(x)
print(x.dtype)

[3.+1.j  1.-2.j  2.+2.2j]
complex128


In [10]:
#unicode
x = np.array([9, 8, 7, 6], dtype = 'U')
print(x)
print(x.dtype)

['9' '8' '7' '6']
<U1


In [11]:
#unsloved integer
x = np.array([9, 8, 7, 6], dtype = 'uint8')
print(x)
print(x.dtype)

[9 8 7 6]
uint8


In [12]:
#object
x = np.array([[9, 8], [7, 1], [6.9, 4.2], ['dude', 'bruh']], dtype = 'O')
print(x)
print(x.dtype)

[[9 8]
 [7 1]
 [6.9 4.2]
 ['dude' 'bruh']]
object
